services:
  converterapp:
    container_name: converterapp
    image: converterapp:latest
    restart: always
    user: "1000:1000"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
